name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (для кращої збірки образів)
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        run: docker-compose build

      - name: Run tests with docker-compose
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --abort-on-container-exit --exit-code-from test

      - name: Cleanup
        if: always()
        run: docker-compose down -v
