name: Build and Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build containers
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml build

      - name: Run integration tests
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test

      - name: Clean up
        if: always()
        run: docker-compose down -v
